version: '3.5'

services: 
  frontend:
    build: 
      context: ./ml-kurkkumopo-frontend/
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
  
  training:
    build: 
      context: ./ml-kurkkumopo-training/
      dockerfile: Dockerfile
    volumes: 
      - data:/src/data
      - model:/src/model
      - imgs:/src/imgs
  backend:
    build:
      context: ./ml-kurkkumopo-backend/
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"
    volumes: 
      - model:/src/model
    depends_on: 
      - training

volumes: 
  data:
  model:
  imgs:

    
