version: '3.0'

services:
  frontend:
    build: 
      context: ./example-frontend/
      dockerfile: dockerfile
    ports: 
      - 5000:5000
    command: ["serve","-s", "-l", "5000","build"]
    
  backend:
    build: 
      context: ./example-backend/
      dockerfile: dockerfile
    ports: 
      - 8080:8080 
    environment: 
      - REQUEST_ORIGIN=http://127.0.0.1:5000
      - PORT=8080
      - REDIS_HOST=redis
    command: [ "./server" ]

  
  redis:
    image: redis
    ports: 
      - 6379:6379
    restart: unless-stopped

