FROM node:14-alpine

WORKDIR /usr/local/app

COPY package.json .
COPY package-lock.json .

RUN npm install

RUN npm install -g serve

COPY . .

RUN npm run build

EXPOSE 5000

CMD ["serve","-s", "-l", "5000","build"]